apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: netflow-api
    tier: backend
  type: NodePort
  externalIPs:
  - <external-ip>
  ports:
  - protocol: TCP
    port: 8080 ## 內部訪問用
    targetPort: 8080 ## container port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflow-api
  labels:
    app: netflow-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netflow-api
      tier: backend
  template:
    metadata:
      labels:
        app: netflow-api
        tier: backend
    spec:
      imagePullSecrets:
      - name: gitlab-auth
      containers:
      - name: netflow-api
        image: "registry.gitlab.com/ashspencil2014/netflow_api:v0.0.2"
        ports:
        - containerPort: 8080
